import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    dashboard: "Instances",
    newBuild: "New Build",
    files: "Files",
    logout: "Log out",
    uploadTitle: "Upload New Build",
    uploadDesc: "Drag & drop ZIP artifact here",
    deploy: "Deploy Build",
    cancel: "Cancel",
    fileManager: "File Manager",
    uploadFile: "Upload Files",
    searchPlaceholder: "Search files...",
    deleteConfirm: "Are you sure you want to delete this?",
    size: "Size",
    actions: "Actions",
    noInstances: "No active instances found. Create one!",
    manageFiles: "Manage Files",
    deleteInstance: "Delete Instance",
    categoryAll: "All Files",
    categoryMods: "Mods",
    categoryConfigs: "Configs",
    categoryShaders: "Shaders",
    categoryResources: "Resource Packs",
    categoryScripts: "Scripts",
    emptyCategory: "This category is empty",
    uploadComplete: "Upload complete",
    success: "success",
    failed: "failed",
    deleteSelected: "Delete Selected",
    deleteSelectedConfirm: "Are you sure you want to delete {count} files?",
    deleteComplete: "Deletion complete",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    instanceSettings: "Instance Settings",
    fileManagerTab: "File Manager",
    syncTab: "Synchronization (SFTP)",
    manualSyncWarning: "Manual Synchronization",
    manualSyncDesc: "After adding or removing mods/configs in File Manager, make sure to click 'Start Synchronization'. There is no automatic server update to avoid accidental overwrites.",
    connectionSettings: "Connection Settings",
    host: "Host (IP)",
    port: "Port",
    sftpLogin: "SFTP Login",
    sftpPassword: "SFTP Password",
    whatToSync: "What to synchronize?",
    modsFolder: "Mods (mods)",
    configFolder: "Configs (config)",
    scriptsFolder: "Scripts (scripts)",
    shadersFolder: "Shaders",
    resourcesFolder: "Resource Packs",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully!",
    saveError: "Save error: ",
    syncDescription: "Synchronization will compare local files in MinIO with remote files on the server. New files will be uploaded, locally deleted files will be removed from the server.",
    startSync: "Start Synchronization",
    syncing: "Synchronizing...",
    syncConfirm: "Are you sure? This will overwrite files on the game server.",
    operationLog: "Operation Log",
    live: "LIVE",
    waitingForStart: "Waiting to start... Logs will appear here.",
    syncInitializing: "Initializing synchronization for",
    connectingSFTP: "Connecting to SFTP (this may take 10-20 sec)...",
    syncSuccess: "SYNCHRONIZATION COMPLETED SUCCESSFULLY!",
    syncError: "ERROR: ",
    fileNamePath: "File Name / Path",
    loadingFiles: "Loading file list...",
    edit: "Edit",
    delete: "Delete",
    dashboardSubtitle: "Server and Build Management",
    filesCount: "Files",
    settings: "Settings",
    sftpSection: "SFTP (File Transfer)",
    rconSection: "RCON (Remote Console)",
    rconDescription: "RCON is a protocol for sending commands to the Minecraft server console remotely. It allows the launcher to safely stop the server before file updates to prevent data corruption.",
    useSftpHost: "Use SFTP Host address",
    rconPasswordPlaceholder: "Enter RCON password",
    rconPort: "RCON Port",
    enableRcon: "Enable RCON Support",
    quickActions: "Quick Actions",
    sendStop: "Send 'stop' command",
    sendStopConfirm: "Are you sure you want to stop the server?",
    stoppingServer: "Stopping server...",
    serverStopped: "Stop command sent.",
    contentFiles: "Game Content",
    systemFiles: "System Files",
    saveSuccessTitle: "Saved",
    saveSuccessMessage: "Connection settings have been updated.",
    syncConfirmTitle: "Start Synchronization?",
    syncConfirmMessage: "This action will overwrite files on the remote server. Ensure you have a backup if needed.",
    confirmAction: "Confirm & Start",
    cancelAction: "Cancel",
    serverTypeTitle: "Select Server Type",
    typeHosting: "Hosting",
    typeHostingDesc: "Managed hosting with built-in RCON support",
    typeVps: "VPS / Dedicated",
    typeVpsDesc: "Self-hosted server, manual RCON configuration",
    hostingGuideTitle: "Hosting Setup Guide",
    vpsGuideTitle: "VPS Setup Guide",
    hostingGuideStep1: "Log in to your hosting control panel",
    hostingGuideStep2: "Find the server.properties file in your file manager",
    hostingGuideStep3: "RCON is usually pre-configured. If not, enable it and set a password",
    hostingGuideStep4: "Enter the RCON password in the settings above",
    vpsGuideStep1: "Edit your server.properties file and add/enable these lines:",
    vpsGuideStep2: "Restart your Minecraft server",
    vpsGuideStep4: "Enter the RCON password in the settings above",
    whereToFind: "Where to find?",
    deleteModalTitle: "Delete Instance",
    deleteRemoteOption: "Also delete files from game server (SFTP)",
    deleteRemoteWarning: "Warning: This will permanently remove mods, configs, and scripts from the remote host.",
    confirmDelete: "Delete Forever",
    deleting: "Deleting..."
  },
  ru: {
    dashboard: "Сборки",
    newBuild: "Новая сборка",
    files: "Файлов",
    logout: "Выйти",
    uploadTitle: "Загрузка сборки",
    uploadDesc: "Перетащите ZIP архив сюда",
    deploy: "Развернуть сборку",
    cancel: "Отмена",
    fileManager: "Файловый менеджер",
    uploadFile: "Загрузить файлы",
    searchPlaceholder: "Поиск (например: jei, ic2)...",
    deleteConfirm: "Вы уверены, что хотите удалить это? Действие необратимо.",
    size: "Размер",
    actions: "Действия",
    noInstances: "Нет активных сборок. Создайте первую!",
    manageFiles: "Управление файлами",
    deleteInstance: "Удалить сборку",
    categoryAll: "Все файлы",
    categoryMods: "Моды",
    categoryConfigs: "Конфиги",
    categoryShaders: "Шейдеры",
    categoryResources: "Ресурспаки",
    categoryScripts: "Скрипты",
    emptyCategory: "В этой категории пока пусто",
    uploadComplete: "Загрузка завершена",
    success: "успешно",
    failed: "ошибок",
    deleteSelected: "Удалить выбранные",
    deleteSelectedConfirm: "Вы уверены, что хотите удалить {count} файлов?",
    deleteComplete: "Удаление завершено",
    selectAll: "Выбрать все",
    deselectAll: "Снять выделение",
    instanceSettings: "Настройки Сборки",
    fileManagerTab: "Файловый менеджер",
    syncTab: "Синхронизация (SFTP)",
    manualSyncWarning: "Ручная Синхронизация",
    manualSyncDesc: "После добавления или удаления модов/конфигов в Файловом менеджере, обязательно нажмите кнопку 'Начать синхронизацию'. Автоматического обновления игрового сервера нет, чтобы избежать случайных перезаписей.",
    connectionSettings: "Настройки Подключения",
    host: "Хост (IP)",
    port: "Порт",
    sftpLogin: "SFTP Логин",
    sftpPassword: "SFTP Пароль",
    whatToSync: "Что синхронизировать?",
    modsFolder: "Моды (mods)",
    configFolder: "Конфиги (config)",
    scriptsFolder: "Скрипты (scripts)",
    shadersFolder: "Шейдеры",
    resourcesFolder: "Ресурспаки",
    saveSettings: "Сохранить настройки",
    settingsSaved: "Настройки успешно сохранены!",
    saveError: "Ошибка сохранения: ",
    syncDescription: "Синхронизация сравнит локальные файлы в MinIO с удаленными файлами на сервере. Новые файлы будут загружены, удаленные локально — будут удалены и с сервера.",
    startSync: "Начать синхронизацию",
    syncing: "Синхронизация...",
    syncConfirm: "Вы уверены? Это перезапишет файлы на игровом сервере.",
    operationLog: "Лог операций",
    live: "LIVE",
    waitingForStart: "Ожидание запуска... Логи появятся здесь.",
    syncInitializing: "Инициализация синхронизации для",
    connectingSFTP: "Устанавливаю соединение с SFTP (это может занять 10-20 сек)...",
    syncSuccess: "СИНХРОНИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА!",
    syncError: "ОШИБКА: ",
    fileNamePath: "Имя файла / Путь",
    loadingFiles: "Загрузка списка файлов...",
    edit: "Редактировать",
    delete: "Удалить",
    dashboardSubtitle: "Управление серверами и сборками",
    filesCount: "Файлов",
    settings: "Настройки",
    sftpSection: "SFTP (Передача файлов)",
    rconSection: "RCON (Удаленная консоль)",
    rconDescription: "RCON — это протокол для отправки команд в консоль Minecraft сервера. Это позволяет лаунчеру безопасно остановить сервер перед обновлением файлов, чтобы избежать повреждения данных.",
    useSftpHost: "Использовать адрес SFTP",
    rconPasswordPlaceholder: "Введите RCON пароль",
    rconPort: "RCON Порт",
    enableRcon: "Включить поддержку RCON",
    quickActions: "Быстрые действия",
    sendStop: "Отправить команду 'stop'",
    sendStopConfirm: "Вы уверены, что хотите остановить сервер?",
    stoppingServer: "Останавливаю сервер...",
    serverStopped: "Команда остановки отправлена.",
    contentFiles: "Игровой контент",
    systemFiles: "Системные файлы",
    saveSuccessTitle: "Сохранено",
    saveSuccessMessage: "Настройки подключения обновлены.",
    syncConfirmTitle: "Запустить синхронизацию?",
    syncConfirmMessage: "Это действие перезапишет файлы на удаленном сервере. Убедитесь, что у вас есть бэкап, если это необходимо.",
    confirmAction: "Подтвердить и начать",
    cancelAction: "Отмена",
    serverTypeTitle: "Выберите тип сервера",
    typeHosting: "Хостинг",
    typeHostingDesc: "Управляемый хостинг со встроенной поддержкой RCON",
    typeVps: "VPS / Dedicated",
    typeVpsDesc: "Самостоятельно размещённый сервер, ручная настройка RCON",
    hostingGuideTitle: "Руководство по настройке хостинга",
    vpsGuideTitle: "Руководство по настройке VPS",
    hostingGuideStep1: "Войдите в панель управления вашего хостинга",
    hostingGuideStep2: "Найдите файл server.properties в файловом менеджере",
    hostingGuideStep3: "RCON обычно уже настроен. Если нет, включите его и установите пароль",
    hostingGuideStep4: "Введите пароль RCON в настройках выше",
    vpsGuideStep1: "Отредактируйте файл server.properties и добавьте/включите эти строки:",
    vpsGuideStep2: "Перезагрузите ваш Minecraft сервер",
    vpsGuideStep4: "Введите пароль RCON в настройках выше",
    whereToFind: "Где найти?",
    deleteModalTitle: "Удаление Сборки",
    deleteRemoteOption: "Также удалить файлы с игрового сервера (SFTP)",
    deleteRemoteWarning: "Внимание: Это навсегда удалит моды, конфиги и скрипты с удаленного сервера.",
    confirmDelete: "Удалить навсегда",
    deleting: "Удаление..."
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ru");

  const toggleLang = () => {
    const newLang = lang === "ru" ? "en" : "ru";
    setLang(newLang);
    localStorage.setItem("lang", newLang);
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);