import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    dashboard: "Instances",
    newBuild: "New Build",
    files: "Files",
    logout: "Log out",
    uploadTitle: "Upload New Build",
    uploadDesc: "Drag & drop ZIP artifact here",
    deploy: "Deploy Build",
    cancel: "Cancel",
    fileManager: "File Manager",
    uploadFile: "Upload Files",
    searchPlaceholder: "Search files...",
    deleteConfirm: "Are you sure you want to delete this?",
    size: "Size",
    actions: "Actions",
    noInstances: "No active instances found. Create one!",
    manageFiles: "Manage Files",
    deleteInstance: "Delete Instance",
    categoryAll: "All Files",
    categoryMods: "Mods",
    categoryConfigs: "Configs",
    categoryShaders: "Shaders",
    categoryResources: "Resource Packs",
    categoryScripts: "Scripts",
    emptyCategory: "This category is empty",
    uploadComplete: "Upload complete",
    success: "success",
    failed: "failed",
    deleteSelected: "Delete Selected",
    deleteSelectedConfirm: "Are you sure you want to delete {count} files?",
    deleteComplete: "Deletion complete",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    instanceSettings: "Instance Settings",
    fileManagerTab: "File Manager",
    syncTab: "Synchronization (SFTP)",
    manualSyncWarning: "Manual Synchronization",
    manualSyncDesc: "After adding or removing mods/configs in File Manager, make sure to click 'Start Synchronization'. There is no automatic server update to avoid accidental overwrites.",
    connectionSettings: "Connection Settings",
    host: "Host (IP)",
    port: "Port",
    sftpLogin: "SFTP Login",
    sftpPassword: "SFTP Password",
    whatToSync: "What to synchronize?",
    modsFolder: "Mods (mods)",
    configFolder: "Configs (config)",
    scriptsFolder: "Scripts (scripts)",
    shadersFolder: "Shaders",
    resourcesFolder: "Resource Packs",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully!",
    saveError: "Save error: ",
    actions: "Actions",
    syncDescription: "Synchronization will compare local files in MinIO with remote files on the server. New files will be uploaded, locally deleted files will be removed from the server.",
    startSync: "Start Synchronization",
    syncing: "Synchronizing...",
    syncConfirm: "Are you sure? This will overwrite files on the game server.",
    operationLog: "Operation Log",
    live: "LIVE",
    waitingForStart: "Waiting to start... Logs will appear here.",
    syncInitializing: "Initializing synchronization for",
    connectingSFTP: "Connecting to SFTP (this may take 10-20 sec)...",
    syncSuccess: "SYNCHRONIZATION COMPLETED SUCCESSFULLY!",
    syncError: "ERROR: ",
    fileNamePath: "File Name / Path",
    loadingFiles: "Loading file list...",
    edit: "Edit",
    delete: "Delete",
    dashboardSubtitle: "Server and Build Management",
    filesCount: "Files",
    settings: "Settings"
  },
  ru: {
    dashboard: "Сборки",
    newBuild: "Новая сборка",
    files: "Файлов",
    logout: "Выйти",
    uploadTitle: "Загрузка сборки",
    uploadDesc: "Перетащите ZIP архив сюда",
    deploy: "Развернуть сборку",
    cancel: "Отмена",
    fileManager: "Файловый менеджер",
    uploadFile: "Загрузить файлы",
    searchPlaceholder: "Поиск (например: jei, ic2)...",
    deleteConfirm: "Вы уверены, что хотите удалить это? Действие необратимо.",
    size: "Размер",
    actions: "Действия",
    noInstances: "Нет активных сборок. Создайте первую!",
    manageFiles: "Управление файлами",
    deleteInstance: "Удалить сборку",
    categoryAll: "Все файлы",
    categoryMods: "Моды",
    categoryConfigs: "Конфиги",
    categoryShaders: "Шейдеры",
    categoryResources: "Ресурспаки",
    categoryScripts: "Скрипты",
    emptyCategory: "В этой категории пока пусто",
    uploadComplete: "Загрузка завершена",
    success: "успешно",
    failed: "ошибок",
    deleteSelected: "Удалить выбранные",
    deleteSelectedConfirm: "Вы уверены, что хотите удалить {count} файлов?",
    deleteComplete: "Удаление завершено",
    selectAll: "Выбрать все",
    deselectAll: "Снять выделение",
    instanceSettings: "Настройки Сборки",
    fileManagerTab: "Файловый менеджер",
    syncTab: "Синхронизация (SFTP)",
    manualSyncWarning: "Ручная Синхронизация",
    manualSyncDesc: "После добавления или удаления модов/конфигов в Файловом менеджере, обязательно нажмите кнопку 'Начать синхронизацию'. Автоматического обновления игрового сервера нет, чтобы избежать случайных перезаписей.",
    connectionSettings: "Настройки Подключения",
    host: "Хост (IP)",
    port: "Порт",
    sftpLogin: "SFTP Логин",
    sftpPassword: "SFTP Пароль",
    whatToSync: "Что синхронизировать?",
    modsFolder: "Моды (mods)",
    configFolder: "Конфиги (config)",
    scriptsFolder: "Скрипты (scripts)",
    shadersFolder: "Шейдеры",
    resourcesFolder: "Ресурспаки",
    saveSettings: "Сохранить настройки",
    settingsSaved: "Настройки успешно сохранены!",
    saveError: "Ошибка сохранения: ",
    actions: "Действия",
    syncDescription: "Синхронизация сравнит локальные файлы в MinIO с удаленными файлами на сервере. Новые файлы будут загружены, удаленные локально — будут удалены и с сервера.",
    startSync: "Начать синхронизацию",
    syncing: "Синхронизация...",
    syncConfirm: "Вы уверены? Это перезапишет файлы на игровом сервере.",
    operationLog: "Лог операций",
    live: "LIVE",
    waitingForStart: "Ожидание запуска... Логи появятся здесь.",
    syncInitializing: "Инициализация синхронизации для",
    connectingSFTP: "Устанавливаю соединение с SFTP (это может занять 10-20 сек)...",
    syncSuccess: "СИНХРОНИЗАЦИЯ УСПЕШНО ЗАВЕРШЕНА!",
    syncError: "ОШИБКА: ",
    fileNamePath: "Имя файла / Путь",
    loadingFiles: "Загрузка списка файлов...",
    edit: "Редактировать",
    delete: "Удалить",
    dashboardSubtitle: "Управление серверами и сборками",
    filesCount: "Файлов",
    settings: "Настройки"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  // По умолчанию русский
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ru");

  const toggleLang = () => {
    const newLang = lang === "ru" ? "en" : "ru";
    setLang(newLang);
    localStorage.setItem("lang", newLang);
  };

  // Функция перевода: t('dashboard') -> 'Сборки'
  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);